# Generated by Django 5.2.2 on 2025-06-05 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Executionlog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('binary', models.CharField(max_length=255)),
                ('command', models.CharField(max_length=255)),
                ('stdout', models.TextField()),
                ('stderr', models.TextField()),
                ('status_code', models.IntegerField()),
            ],
        ),
    ]
