# Generated by Django 5.2.2 on 2025-06-06 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='executionlog',
            name='args',
            field=models.JSONField(default=list),
        ),
    ]
