# Generated by Django 5.2.2 on 2025-06-06 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_executionlog_args'),
    ]

    operations = [
        migrations.AlterField(
            model_name='executionlog',
            name='args',
            field=models.JSONField(default=dict),
        ),
    ]
